### PR TITLE
Use fastprogress

### PR DESCRIPTION
**Pull request by andersy005**
Checklist

- [x] Passes `pre-commit run --all-files`
- [ ] Tests added / passed

- supersedes #237

### CODE REVIEW

**Comment by jbusecke** [comment]
Just gave it a quick go and got some mixed results. The progressbar stays in one piece, but appears in between my messages. 
image

I could totally live with this though.

**Comment by andersy005** [comment]
>  The progressbar stays in one piece, but appears in between my messages.

I will investigate this before merging, and will let you know if there's any workaround.

**Comment by andersy005** [comment]
@jbusecke, I may have found a solution for your problem. 

When you get a chance, can you try replacing your print statements with

```python
print(..., end=' ') 
```

**Comment by andersy005** [comment]
I am going to merge this for now. We can revisit it if any other issues show up

**Pull request merged**
