### PR TITLE
Added support for cordex datafiles, and documented process in addingdatasets.ipynb

### PR DESCRIPTION
**Pull request by jukent**

### CODE REVIEW

**Comment by andersy005** [comment]
@jukent, thank you for putting this together! I am looking forward to intake-esm having a great `how to guide` for adding new datasets..

You will need to merge changes from master into your branch with `git pull upstream master && git push`. Let me know when this is ready for review

**Comment by jukent** [comment]
Thanks. I will be in for a few hours tomorrow morning and I will fix it.

**Comment by jukent** [comment]
This is in regards to issue #101

**Comment by martindurant** [comment]
intake/intake-xarray#46  works as intended for you?

**Comment by andersy005** [comment]
@martindurant 

I expect it to work since the error is coming from

```bash
intake_esm/source.py:1: in <module>
    import intake_xarray
/usr/local/envs/intake-esm-dev/lib/python3.7/site-packages/intake_xarray/__init__.py:8: in <module>
    from .xzarr import ZarrSource
/usr/local/envs/intake-esm-dev/lib/python3.7/site-packages/intake_xarray/xzarr.py:2: in <module>
    from dask.bytes.core import get_fs, infer_options, update_storage_options
E   ImportError: cannot import name 'get_fs' from 'dask.bytes.core' (/usr/local/envs/intake-esm-dev/lib/python3.7/site-packages/dask/bytes/core.py)
```

**Comment by martindurant** [comment]
OK, I'll merge and release, and we can iterate again if necessary.

**Comment by andersy005** [comment]
@martindurant, when you get time, can you merge https://github.com/conda-forge/intake-xarray-feedstock/pull/2?

**Pull request merged**
