### PR TITLE
CMIP6 integration 

### PR DESCRIPTION
**Pull request by andersy005**
- Addresses #43

### CODE REVIEW

**Comment by andersy005** [comment]
@matt-long, this is ready for review.  @naomi-henderson, feel free to chime in. Below is an example of how this works so far:


```python
In [1]: import intake                                                                                                                            

In [2]: from intake_esm import config                                                                                                            

In [3]: config.set({'database-directory': './tests/test_collections'})                                                                           
Out[3]: <intake_esm.config.set at 0x11b8d80f0>

In [4]: collection_definition = { 
   ...:             'name': 'cmip6_test_collection', 
   ...:             'collection_type': 'cmip6', 
   ...:             'data_sources': { 
   ...:                 'root_dir': { 
   ...:                     'name': 'GLADE', 
   ...:                     'loc_type': 'posix', 
   ...:                     'direct_access': True, 
   ...:                     'urlpath': './tests/sample_data/cmip/CMIP6', 
   ...:                 } 
   ...:             }, 
   ...:         }                                                                                                                                

In [5]: col = intake.open_esm_metadatastore( 
   ...:             collection_input_definition=collection_definition, overwrite_existing=True 
   ...:         )                                                                                                                                
Getting list of directories
directories: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 318/318 [00:00<00:00, 523054.38it/s]
Found 90 directories
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 14 columns):
activity_id       90 non-null object
experiment_id     90 non-null object
file_basename     90 non-null object
file_dirname      90 non-null object
file_fullpath     90 non-null object
grid_label        90 non-null object
institution_id    90 non-null object
member_id         90 non-null object
mip_era           90 non-null object
source_id         90 non-null object
table_id          90 non-null object
time_range        90 non-null object
variable_id       90 non-null object
version           90 non-null object
dtypes: object(14)
memory usage: 9.9+ KB
None
Persisting cmip6_test_collection at : ./tests/test_collections/cmip6/cmip6_test_collection.csv

In [6]: col.df.head()                                                                                                                            
Out[6]: 
  activity_id experiment_id                                      file_basename  ...     time_range    variable_id    version
0        CMIP       1pctCO2  mrso_Lmon_CNRM-CM6-1_1pctCO2_r1i1p1f2_gr_18500...  ...  185001-199912           mrso  v20180626
1        CMIP       1pctCO2  mrfso_Lmon_CNRM-CM6-1_1pctCO2_r1i1p1f2_gr_1850...  ...  185001-199912          mrfso  v20180626
2        CMIP       1pctCO2  gpp_Lmon_CNRM-CM6-1_1pctCO2_r1i1p1f2_gr_185001...  ...  185001-199912            gpp  v20180626
3        CMIP       1pctCO2  evspsblveg_Lmon_CNRM-CM6-1_1pctCO2_r1i1p1f2_gr...  ...  185001-199912     evspsblveg  v20180626
4        CMIP       1pctCO2  landCoverFrac_Lmon_CNRM-CM6-1_1pctCO2_r1i1p1f2...  ...  185001-199912  landCoverFrac  v20180626

[5 rows x 14 columns]

In [8]: cat = col.search( 
   ...:             source_id=['CNRM-ESM2-1', 'GISS-E2-1-G'], 
   ...:             experiment_id='historical', 
   ...:             variable_id=['gpp', 'tasmax'], 
   ...:         ) 
   ...:  
   ...:                                                                                                                                          

In [9]: cat.query_results.head()                                                                                                                 
Out[9]: 
   activity_id experiment_id                                      file_basename  ...     time_range variable_id    version
55        CMIP    historical  gpp_Lmon_historical_GISS-E2-1-G_r10i1p1f1_gn_2...  ...  200101-201412         gpp  v20181015
52        CMIP    historical  gpp_Lmon_historical_GISS-E2-1-G_r1i1p1f1_gn_20...  ...  200101-201412         gpp  v20181015
84        CMIP    historical  tasmax_Amon_CNRM-ESM2-1_historical_r3i1p1f2_gr...  ...  185001-201412      tasmax  v20190125
41        CMIP    historical  gpp_Lmon_historical_GISS-E2-1-G_r4i1p1f1_gn_20...  ...  200101-201412         gpp  v20181015
40        CMIP    historical  gpp_Lmon_historical_GISS-E2-1-G_r6i1p1f1_gn_20...  ...  200101-201412         gpp  v20181015

[5 rows x 14 columns]

In [10]: ds = cat.to_xarray(decode_times=False, chunks={'member_id': 1, 'time': 1, 'lat': 2, 'lon': 2})                                          
dataset: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 17.66it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 86.11it/s]
In [11]: ds                                                                                                                                      
Out[11]: 
{'CNRM-CERFACS.CNRM-ESM2-1.historical.Amon.gr': <xarray.Dataset>
 Dimensions:      (axis_nbounds: 2, lat: 5, lon: 5, time: 2)
 Coordinates:
   * lat          (lat) float64 -88.93 -87.54 -86.14 -84.74 -83.34
   * lon          (lon) float64 0.0 1.406 2.812 4.219 5.625
     height       float64 ...
   * time         (time) float64 15.5 45.0
     time_bounds  (time, axis_nbounds) float64 ...
 Dimensions without coordinates: axis_nbounds
 Data variables:
     tasmax       (time, lat, lon) float32 ...
 Attributes:
     Conventions:            CF-1.7 CMIP-6.2
     creation_date:          2018-07-04T11:40:03Z
     description:            CMIP6 historical
     title:                  CNRM-ESM2-1 model output prepared for CMIP6 / CMI...
     activity_id:            CMIP
     contact:                contact.cmip@meteo.fr
     data_specs_version:     01.00.21
     dr2xml_version:         1.10
     experiment_id:          historical
     experiment:             all-forcing simulation of the recent past
     external_variables:     areacella
     forcing_index:          2
     frequency:              mon
     further_info_url:       https://furtherinfo.es-doc.org/CMIP6.CNRM-CERFACS...
     grid:                   data regridded to a T127 gaussian grid (128x256 l...
     grid_label:             gr
     nominal_resolution:     250 km
     initialization_index:   1
     institution_id:         CNRM-CERFACS
     institution:            CNRM (Centre National de Recherches Meteorologiqu...
     license:                CMIP6 model data produced by CNRM-CERFACS is lice...
     mip_era:                CMIP6
     parent_experiment_id:   piControl
     parent_mip_era:         CMIP6
     parent_activity_id:     CMIP
     parent_source_id:       CNRM-ESM2-1
     parent_time_units:      days since 1850-01-01 00:00:00
     branch_method:          standard
     branch_time_in_parent:  33237.0
     branch_time_in_child:   0.0
     physics_index:          1
     product:                model-output
     realization_index:      3
     realm:                  atmos
     references:             http://www.umr-cnrm.fr/cmip6/references
     source:                 CNRM-ESM2-1 (2017):  aerosol: TACTIC_v2 atmos: Ar...
     source_id:              CNRM-ESM2-1
     source_type:            AOGCM BGC AER CHEM
     sub_experiment_id:      none
     sub_experiment:         none
     table_id:               Amon
     variable_id:            tasmax
     variant_label:          r3i1p1f2
     EXPID:                  CNRM-ESM2-1_historical_r3i1p1f2
     CMIP6_CV_version:       cv=6.2.3.0-7-g2019642
     dr2xml_md5sum:          d6225e658d7de0912fca2a4293dbe2a7
     xios_commit:            1442-shuffle
     nemo_gelato_commit:     49095b3accd5d4c_6524fe19b00467a
     arpege_minor_version:   6.3.2
     parent_variant_label:   r1i1p1f2
     history:                2019-03-20 13:58:07.876497 xarray.open_dataset('....
     tracking_id:            hdl:21.14100/f919057a-91e1-4575-b82d-6737458d005a,
 'NASA-GISS.GISS-E2-1-G.historical.Lmon.gn': <xarray.Dataset>
 Dimensions:    (bnds: 2, lat: 5, lon: 5, member_id: 5, time: 2)
 Coordinates:
   * time       (time) float64 5.513e+04 5.516e+04
   * lat        (lat) float64 -89.0 -87.0 -85.0 -83.0 -81.0
   * lon        (lon) float64 1.25 3.75 6.25 8.75 11.25
   * member_id  (member_id) <U9 'r10i1p1f1' 'r1i1p1f1' ... 'r6i1p1f1' 'r7i1p1f1'
 Dimensions without coordinates: bnds
 Data variables:
     time_bnds  (time, bnds) float64 dask.array<shape=(2, 2), chunksize=(1, 2)>
     lat_bnds   (lat, bnds) float64 dask.array<shape=(5, 2), chunksize=(2, 2)>
     lon_bnds   (lon, bnds) float64 dask.array<shape=(5, 2), chunksize=(2, 2)>
     gpp        (member_id, time, lat, lon) float32 dask.array<shape=(5, 2, 5, 5), chunksize=(1, 1, 2, 2)>
 Attributes:
     cmor_version:           3.3.2
     sub_experiment_id:      none
     institution:            Goddard Institute for Space Studies, New York, NY...
     parent_experiment_id:   piControl
     table_info:             Creation Date:(21 March 2018) MD5:f76dbc1e8bf6b7e...
     creation_date:          2018-10-16T16:04:24Z
     physics_index:          1
     source_type:            AOGCM
     experiment:             all-forcing simulation of the recent past
     parent_variant_label:   r1i1p1f1
     Conventions:            CF-1.7 CMIP-6.2
     parent_experiment_rip:  r1i1p1
     variant_label:          r7i1p1f1
     realization_index:      7
     source:                 GISS-E2.1G (2016): \naerosol: Varies with physics...
     forcing_index:          1
     initialization_index:   1
     sub_experiment:         none
     parent_mip_era:         CMIP6
     further_info_url:       https://furtherinfo.es-doc.org/CMIP6.NASA-GISS.GI...
     model_id:               E200f10gF40oQ40
     branch_time_in_parent:  43800.0
     table_id:               Lmon
     data_specs_version:     01.00.23
     title:                  GISS-E2-1-G output prepared for CMIP6
     tracking_id:            hdl:21.14100/4cc50f05-35bf-486f-b36f-634c2b7398b8
     product:                model-output
     activity_id:            CMIP
     parent_activity_id:     CMIP
     nominal_resolution:     250 km
     variable_id:            gpp
     external_variables:     areacella
     realm:                  land
     grid_label:             gn
     experiment_id:          historical
     license:                CMIP6 model data produced by NASA Goddard Institu...
     history:                2019-03-20 13:58:07.890109 xarray.open_dataset('....
     grid:                   atmospheric grid: 144x90, ocean grid: 288x180
     references:             https://data.giss.nasa.gov/modelE/cmip6
     contact:                Kenneth Lo (cdkkl@giss.nasa.gov)
     branch_method:          standard
     source_id:              GISS-E2-1-G
     mip_era:                CMIP6
     parent_source_id:       GISS-E2-1-G
     parent_time_units:      days since 4150-1-1
     branch_time_in_child:   0.0
     frequency:              mon
     institution_id:         NASA-GISS}
```

**Comment by naomi-henderson** [comment]
@andersy005 , this is looking great - I like that you are keeping the variables in separate datasets and `intake-esm` handles them both.   I look forward to using it!

**Comment by matt-long** [comment]
@andersy005, based on yesterday's discussion, I presume you're still working on this. Don't let my absence next week hold you up.

**Comment by andersy005** [comment]
@matt-long, this is pretty much done. I am going to merge this PR. Once you are back, we can iterate on needed improvements.

**Pull request merged**
