### PR TITLE
Add support for CAFE

### PR DESCRIPTION
**Pull request by jmunroe**
Added CAFECollection, and cafe collection type with associated tests.

### CODE REVIEW

**Comment by andersy005** [comment]
@jmunroe, I am glad to see this working :) 

Did you get the `to_xarray()` method working?

**Comment by jmunroe** [comment]
Good call. We still need to do some work on the _open_dataset().  I'll do that and add a corresponding test before continuing with this PR.

**Comment by martindurant** [comment]
Can you please provide a link to say what the CAFE collection is, for outsiders such as myself?

**Comment by andersy005** [comment]
@jmunroe, #77 addressed the code duplication issue, and introduced new changes that make extending `intake-esm` very easy. 

With #77, subclasses of `Collection` are required to implement `_get_file_attrs` method only. 
Check https://github.com/NCAR/intake-esm/blob/master/intake_esm/cmip.py out for reference. 

You will also need to update your list of columns in `config.yaml` by adding the following columns 

- resource
- resource_type
- direct_access

Let me know if you have any questions.

**Comment by andersy005** [comment]
Also, we've created a new repository https://github.com/NCAR/intake-esm-datastore for curating collection definitions, i.e. YAML files used to build the collections. 

A user is now able to use collection-definitions from intake-esm-datastore repository. For example:

```python
col = intake.open_esm_metadatastore(collection_input_definition="CESM1-LE")
```

or 

```python
col = intake.open_esm_metadatastore(collection_input_definition="GLADE-CMIP5")
```

`intake-esm` automatically retrieves the YAML file from the `intake-esm-datastore` repository and uses it to build the collection.

 
Therefore, once this PR is merged, we will need to add a `cafe collection definition` file in `intake-esm-datastore`. Here's a CMIP6 collection definition for reference: https://github.com/NCAR/intake-esm-datastore/blob/master/collection-definitions/glade-cmip6-collection.yml

**Comment by andersy005** [comment]
@jmunroe,

Checking in here

Are you planning on pushing new changes here or should we close this PR (in case you changed you mind)?

**Comment by jmunroe** [comment]
Thanks for the reminder. I still intend to come back to this PR.

**Comment by andersy005** [comment]
@jmunroe,

With #135, we re-wrote intake-esm based on `esm-collection-specification`: https://github.com/NCAR/esm-collection-spec/blob/master/collection-spec/collection-spec.md 

As a result, intake-esm doesn't include functionality to build the catalog anymore. It just parses the a collection definition JSON file that conforms to the ems-collection spec. 

This approach is a much better alternative to what we were doing before.

Now we can support an arbitrary number of collections (CMIP5, CMIP6, ERA5, CESM-LENS, etc....) without needing to change the source code. 

See [intake-esm-datastore repo](https://github.com/NCAR/intake-esm-datastore/tree/master/catalogs), and [intake-esm tutorial](https://intake-esm.readthedocs.io/en/latest/notebooks/tutorial.html) for examples of collection definitions and how to use these collections with intake-esm.

**Pull request closed without merging**
