### PR TITLE
Pass `urlpath` through call stack for optional use in `Collection._get_file_attrs(f,urlpath)`

### PR DESCRIPTION
**Pull request by pbranson**
Pull request to to sort collections upon creation and pass urlpath through to _get_file_attrs if the inheriting class expects it.

Due to the change in the interface for _get_file_attrs() tests fail, but not sure about the correct way to approach this - should all the implemented Collection classes be updated as part of this PR?

Tried to maintain backwards compatibility by looking at the function signature, but that doesnt help the tests.

Addresses #106

### CODE REVIEW

**Comment by pbranson** [comment]
My first go at a PR... be gentle ;-)

**Comment by andersy005** [comment]
@pbranson, 

First, thank you for your contribution and welcome! I just ran a quick smoke test, and it works pretty well:

```python
In [16]: from intake.source.utils import reverse_format

In [17]: urlpath = "/glade/scratch/abanihi/lens-aws/atm/daily"

In [18]: pattern = "cesmLE-{experiment}-{variable}.zarr"

In [19]: path_fmt = urlpath+"/"+pattern

In [20]: path = "/glade/scratch/abanihi/lens-aws/atm/daily/cesmLE-20C-FLNS.zarr"

In [21]: reverse_format(path_fmt, path)
Out[21]: {'experiment': '20C', 'variable': 'FLNS'}
```

This looks pretty good to me! I will merge it soon unless there's any objection and or addition needed. 

Cc @matt-long

**Comment by pbranson** [comment]
Thats great! Glad to finally make some contribution to some pangeo tools!

**Comment by andersy005** [comment]
> should all the implemented Collection classes be updated as part of this PR?


@pbranson, 

Thinking more about this, I think that it may be a good idea to go ahead and update collection classes as part of this PR. Let me know if you have time to take a stab at this.

**Comment by andersy005** [comment]
@pbranson, I am merging this change. We'll iterate on those other changes in another PR. 

Thank you again for this useful addition!

**Comment by pbranson** [comment]
That's great! Glad to help, happy to assist with updating existing
collections if required.

I now have a stand alone example working that adjusts collection_types at
runtime so that you don't need to make core.py code changes to add a source
and collection.

**Comment by andersy005** [comment]
> I now have a stand alone example working that adjusts collection_types at
runtime so that you don't need to make core.py code changes to add a source
and collection.

I am interested in seeing how you are doing this. If you can point me to that standalone example, that would be great

**Pull request merged**
